version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ./:/root/opt
    ports:
      - "8080:8080"
      - "8081:8081"